# Generated by Django 4.1 on 2022-10-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_repo", "0003_remove_contact_information_contact_pref_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asd_dsm5",
            name="asd_dsm5_collect",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="asd_dsm5",
            name="asd_dsm5_date_completion",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cgii",
            name="cgi_i_collect",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cgii",
            name="cgi_i_date_completion",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cgis",
            name="cgi_s_collected",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cgis",
            name="cgi_s_date_completion",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eeg",
            name="eeg_attempt",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eeg",
            name="eeg_date_completion",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inclusion_exclusion",
            name="ie_collection_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stop_signal",
            name="ss_collected",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stop_signal",
            name="ss_date_completion",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wasi",
            name="wasi_date_completion",
            field=models.DateField(blank=True, null=True),
        ),
    ]
