# Generated by Django 4.1 on 2022-10-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_study_options_study_study_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompletedVisits",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("record_id", models.CharField(max_length=255)),
                ("instance", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
