# Generated by Django 4.1 on 2022-10-04 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_completedvisits"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CompletedVisits",
            new_name="CompletedVisit",
        ),
    ]
