# Generated by Django 4.1 on 2022-10-04 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_rename_completedvisits_completedvisit"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="completedvisit",
            options={"ordering": ["record_id", "instance"]},
        ),
        migrations.AlterUniqueTogether(
            name="completedvisit",
            unique_together={("record_id", "instance")},
        ),
        migrations.CreateModel(
            name="CreatedInstrument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instrument_name", models.CharField(max_length=255)),
                ("instance", models.IntegerField()),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.completedvisit",
                    ),
                ),
            ],
        ),
    ]
