# Generated by Django 4.1 on 2022-10-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_completedvisit_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="createdinstrument",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="createdinstrument",
            name="successful",
            field=models.BooleanField(default=True),
        ),
    ]
