# Generated by Django 4.1 on 2022-10-21 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_group_alter_study_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="instrument",
            options={"ordering": ["instrument_name"]},
        ),
        migrations.CreateModel(
            name="InstrumentCreationRule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_age",
                    models.FloatField(
                        blank=True, help_text="Leave blank for no min age", null=True
                    ),
                ),
                (
                    "max_age",
                    models.FloatField(
                        blank=True, help_text="Leave blank for no max age", null=True
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank for all groups",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.group",
                    ),
                ),
                (
                    "instruments",
                    models.ManyToManyField(blank=True, to="main.instrument"),
                ),
                (
                    "study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.study"
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
