# Generated by Django 4.1 on 2022-10-21 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_alter_instrument_options_instrumentcreationrule"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="instrumentcreationrule",
            options={"ordering": ["study__study_name", "id"]},
        ),
        migrations.AlterField(
            model_name="instrumentcreationrule",
            name="instruments",
            field=models.ManyToManyField(
                blank=True,
                help_text="Hold ctrl to select multiple",
                to="main.instrument",
            ),
        ),
        migrations.DeleteModel(
            name="StudyInstrument",
        ),
    ]
