# Generated by Django 4.1 on 2023-01-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_alter_instrumentcreationrule_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="instrument",
            name="instrument_field",
            field=models.CharField(
                default="not_set",
                help_text="An API record import must include at least one field, even if it's empty",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
