# Generated by Django 4.1 on 2023-01-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_instrument_instrument_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="completedvisit",
            name="visit_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
