# Generated by Django 4.1 on 2023-12-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_completedvisit_ignore"),
    ]

    operations = [
        migrations.AddField(
            model_name="instrumentcreationrule",
            name="strict_operator",
            field=models.BooleanField(
                choices=[(True, "Yes"), (False, "No")],
                default=False,
                help_text="Select Yes to make the operators strictly less than for max age and strictly greater than for min age.  Select No to include records equal to listed min or max age(s).",
            ),
            preserve_default=False,
        ),
    ]
